Sprint 09
snowsergo/ImageFeed pull request #2
Opened 2022-11-06 00:36 UTC by snowsergo

добавил экран с одним изображением, с изменением масштаба и кнопкой поделиться

2022-11-06 17:53 UTC, mmbabaev commented
Есть warning-и в верстке
<img width="813" alt="Screen Shot 2022-11-06 at 20 51 21" src="https://user-images.githubusercontent.com/12600807/200186852-11d193fd-f97f-4330-bb73-ad11656f1961.png">

2022-11-06 17:58 UTC, mmbabaev commented
https://user-images.githubusercontent.com/12600807/200187031-6c8af51f-c66a-468a-8502-76d124974fe7.mp4

Картинка "съезжает" при зуме

2022-11-06 17:58 UTC, mmbabaev requested changes

2022-11-06 17:58 UTC, mmbabaev commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +    override func viewDidLoad() {
обычно принято override функции писать выше остальных

2022-11-06 21:28 UTC, snowsergo commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +    override func viewDidLoad() {
насчет скролла вроде поправил, но это не точно, не хватает анимации как должно быть правильно

2022-11-06 21:30 UTC, snowsergo commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +    override func viewDidLoad() {
ворнинги тоже убрал, но ворнинга что like button misplace у меня почему то нет

2022-11-07 14:34 UTC, mmbabaev commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +    override func viewDidLoad() {
Про скролл - моя ошибка, давайте вернем как было в предыдущем коммите. В следующих заданиях вы будете улучшать это поведение

2022-11-08 20:47 UTC, merged