Sprint 10
snowsergo/ImageFeed pull request #3
Opened 2022-11-28 22:46 UTC by snowsergo

авторизация, сохранение токена, splash screen

2022-11-29 07:03 UTC, mmbabaev requested changes

2022-11-29 07:03 UTC, mmbabaev commented on ImageFeed/Auth/OAuth2Service.swift
> +                return
нет обработки ошибки decode

2022-11-29 07:03 UTC, mmbabaev commented on ImageFeed/Auth/SplashViewController.swift
> +            }
скачет форматирование. Предлагаю использовать `cmd+A` + `ctrl+I`

2022-11-29 07:03 UTC, mmbabaev commented on ImageFeed/Auth/OAuth2Service.swift
> +                handler(.failure(NetworkError.codeError))
handler вызывается не на главной очереди

2022-11-29 07:03 UTC, mmbabaev commented on ImageFeed/Auth/SplashViewController.swift
> +            self.fetchOAuthToken(code)
можно `self?.fetchOAuthToken(code`

2022-11-29 07:03 UTC, mmbabaev commented on ImageFeed/Resources/Constants.swift
> +let ACCESS_KEY = "sMwlgEfPs_JTrR4USTHssO46g2w52m6z-vRdBTuIvKs"
так не принято в Swift делать константы. Предлагаю так: 
```
enum Constants {
   static let secretKey = ""
   ....
}

2022-11-29 07:03 UTC, mmbabaev commented on ImageFeed/Models/OAuthTokenResponseBody.swift
> +    let access_token: String
вы выше использовали CodingKeys, тут тоже можно это использовать, чтобы писать имена через `camelCase`

2022-11-29 07:03 UTC, mmbabaev commented on ImageFeed/Models/OAuthTokenResponseBody.swift
> +    let access_token: String
Другой вариант - использовать `keyDecodingStrategy/keyEncodingStrategy` 
https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase

2022-11-29 07:14 UTC, mmbabaev commented
<img width="569" alt="Screen Shot 2022-11-29 at 10 06 20" src="https://user-images.githubusercontent.com/12600807/204462746-bb024cf2-da22-45f2-a69d-739d0b822507.png">
Выглядит не очень хорошо, что контент начинается с самого верха. Предлагаю либо сдвинуть topConstraint webView под progressView, еще лучше - использовать navigationController

2022-11-29 07:15 UTC, mmbabaev commented
https://user-images.githubusercontent.com/12600807/204463256-a957cd8b-eeee-4179-bbb3-5292f52761c1.mp4

Сейчас этот экран выглядит не по дизайну и его можно смахнуть вниз и зависнуть на белом экране

2022-11-29 21:13 UTC, snowsergo commented on ImageFeed/Auth/SplashViewController.swift
> +            }
спасибо, вы первый кто подсказал хоть какой то способ форматирвоания)

2022-11-30 16:22 UTC, mmbabaev commented on ImageFeed/Auth/SplashViewController.swift
> +            }
вообще на реальных проектах обычно используют автолинтеры-автоформаттеры
swiftlint
SwiftFormat

2022-11-30 16:28 UTC, mmbabaev commented on ImageFeed/Auth/WebViewViewController.swift
> +    @IBAction func didTapBackButton(_ sender: Any) {
порядок в viewController обычно делают такой: 

1. Properties
2. override funcs
3. IBAction funcs
4. other funcs  


другие типы - сверху или снизу

2022-11-30 16:29 UTC, mmbabaev commented on ImageFeed/Auth/WebViewViewController.swift
> +        super.viewDidDisappear(animated)
ой-ей, так делать плохо, нужно исправить

2022-11-30 16:39 UTC, mmbabaev requested changes

2022-11-30 16:39 UTC, mmbabaev commented on ImageFeed/Auth/WebViewViewController.swift
> +        super.viewWillAppear(animated)
тут тоже нужно исправить

2022-12-01 07:16 UTC, mmbabaev approved these changes

2022-12-01 07:16 UTC, mmbabaev commented on ImageFeed/Auth/SplashViewController.swift
> +                self.tokenStorage.token = code
хорошо, что добавили, я проглядел

2022-12-04 10:24 UTC, merged