12 спринт
snowsergo/ImageFeed pull request #5
Opened 2022-12-27 19:38 UTC by snowsergo

загрузка картинок, лайки, выход из профиля

2022-12-27 21:06 UTC, ABashkirova requested changes
Визуальные особенности, которые хорошо бы исправить
<img width="517" alt="Снимок экрана 2022-12-27 в 22 26 09" src="https://user-images.githubusercontent.com/20269264/209722260-0b50decd-4b0e-4181-9733-de166fd65c5e.png">

<img width="517" alt="Снимок экрана 2022-12-27 в 22 26 22" src="https://user-images.githubusercontent.com/20269264/209722253-d9e334ab-cbb1-4061-b8de-04892c53be06.png">

По идее, память должна очищаться при загрузке большого количества картинок. Пока, только растет, хотя должен и кэш у кингфишера очищаться. Советую покапать в эту сторону тоже. 
<img width="724" alt="Снимок экрана 2022-12-27 в 22 32 07" src="https://user-images.githubusercontent.com/20269264/209722285-635ccc62-24b4-4ffa-ba04-3fef4a9cf4a9.png">

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    @IBAction func likeButtonClicked(_ sender: Any) {
приватным надо сделать

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    func setIsLiked(isLiked: Bool) {
давай договоримся здесь один раз и на всегда: между логическими блоками максимум и минимум – 1 строка :)

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        cellImage.kf.cancelDownloadTask()
Это хороший метод, чтобы сделать подобную задачу, а также здесь хорошо сбрасывать само изображение из cellImage, стейт кнопки и содержимое даты. Чтобы при быстром скроле не проскакивало стейтов из предыдущих ячеек

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        UIBlockingProgressHUD.dismiss()
не очень хорошо, что какая-то маленькая ячейка управляет довольно-таки глобальной сущностью. Код наверняка станет сильно связанным, давай использовать HUD только на вью контроллерах. Так его будет несложно выкорчевать и заменить чем-то другим.

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +    static let DidChangeNotification = Notification.Name(rawValue: "ImagesListServiceDidChange")
Все еще не нравится нарушение общепринятой нормы именовать свойства/переменные в нижнем camelCase. Верхний CamelCase используем только для типов: структуры, енамы, классы, typealeas, но не для констант

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +                    self.notificationCenter
self используется, а слабо ссылку не держишь, какой цели придерживаешься?

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +                    return
Этот ретурн выйдет из тела замыкания, но та как это и так конец замыкания – он излишний
```suggestion
                case .failure:
                    self.task = nil
```

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +                    UIBlockingProgressHUD.dismiss()
Аналогично комментарию с ячейкой – этому коду здесь не место. Сервисы должны максимально минимизировать пересечение с UI-фреймворками

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        if (indexPath.row + 1 == photos.count){
```suggestion
        if indexPath.row + 1 == photos.count {
```

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        if (indexPath.row + 1 == photos.count){
и тоже бы в guard запихнуть

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        if oldCount != newCount {
почему бы не сделать в guard? код будет иметь уровень вложенности на одну меньше)

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/Profile/ProfileViewController.swift
>      @IBAction func didTapLogoutButton(_ sender: Any) {
private

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/Profile/ProfileViewController.swift
> +    static func clean() {
почему статика? Точно ли этот код должен быт здесь или можно в сервис перенести?

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +                        )
можно сделать приватный extension к PhotoResult, где сделать функцию convertToViewModel() -> Photo. Это позволит упростить эту функцию – станет короче и площе, быстрее будет считываться суть 

так же, в swift поддерживает функциональный подход. Вместо цикла for-each можно написать короче
let newPhotos = images.map { $0.convertToViewModel() } 
self.photos.append(newPhotos)

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +                        self.photos.append(convertedImage);
`;;;)`

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +struct UrlsResult: Codable {
структуры бы вынести в отдельные файлы, разместить в директории Models

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/Auth/SplashViewController.swift
>          alertPresenter.showAlert(
У меня в процессе проверки все сломалось и я заметила такой баг:
когда ты получаешь ошибку с текущим токеном, ты выкидываешь нас сюда – пользовательница (я) жмет на кнопку "попробовать еще раз" и повторяет действие с тем же токеном. 

А по-хорошему бы, забыть про этот токен (может быть с какой-то попытки?) и проделать принудительный разлогин, кинуть на авторизацию.

Иначе я по кругу хожу, пришлось приложение удалять.

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/Auth/SplashViewController.swift
>          alertPresenter.showAlert(
Не уверена, но кажется привысила количество запросов
<img width="517" alt="Снимок экрана 2022-12-27 в 22 39 57" src="https://user-images.githubusercontent.com/20269264/209720043-32301ae6-b510-439c-8e75-4a24ff30a0c7.png">

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +        if self.task != nil {return}
Фигурыные скобки сопровождаются пробелами
```suggestion
        if self.task != nil { return }
```

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            imagesListService.fetchPhotosNextPage(token: token)
Я не уверена, но кажется здесь кроется бажок: приложение только открылось, а уже убежало три запроса по 10 фоток. Кажется задумывалось то поведение другое: при скроле, отправлять доп запрос, и только на последней ячейке подгружать новую порцию. 
Возможно так происходит из-за подтормаживающей анимации (когда ячейки первым кадом с нулевым размером успевают показаться на экране и этот метод отрабатывает). 

Предлагаю проверить сценарии:
- срабатывает ли метод, когда ты находишься на последней ячейке (например 3 страницы загрузил)
- сколько раз отработает этот метод при старте приложения (сама не могу протестировать)

<img width="517" alt="Снимок экрана 2022-12-27 в 22 26 09" src="https://user-images.githubusercontent.com/20269264/209720335-c664de27-ab19-4620-9987-c6fcc0739ae3.png">

2022-12-27 21:06 UTC, ABashkirova commented on ImageFeed/Profile/ProfileViewController.swift
> +        ProfileViewController.clean()
Да, так точно не хорошо: давай вынесем это в отдельный сервис или поместим к уже существуещему

2023-01-05 19:20 UTC, snowsergo commented on ImageFeed/ImagesList/ImagesListService.swift
> +                    self.notificationCenter
тут я не понял что именно не так

2023-01-05 19:52 UTC, snowsergo commented on ImageFeed/ImagesList/ImagesListService.swift
> +struct UrlsResult: Codable {
разве не удобнее видеть тип с которым работает сервис сразу в верху сервиса без  лишних переходов между файлами?

2023-01-06 00:17 UTC, snowsergo commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            imagesListService.fetchPhotosNextPage(token: token)
добавил плейсхолдер в загрузку картинок и проблема исчезла

2023-01-08 18:32 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +        : lastLoadedPage! + 1
почему бы не положить в lastLoadedPage при инициализации 0, и при завершении загрузки страницы, делать инкремент?

Старайся тернарник умещать в короткую и понятную строчку. Если приходится так разбивать – скорее всего лучше использовать полноценный оператор 

ну и сравнивать с нилом чтобы потом тут же форс анврапнуть – моветон, давай избегать такой код

2023-01-08 18:33 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +                    }
```suggestion
                    if let lastLoadedPage = self.lastLoadedPage {
                        self.lastLoadedPage! = lastLoadedPage  + 1
                    } else {
                        self.lastLoadedPage = 1
                    }
```

2023-01-08 18:35 UTC, ABashkirova commented on ImageFeed/Models/PhotoResult.swift
> +        }()
[Операция создания date formatter достаточно дорогая](https://sarunw.com/posts/how-expensive-is-dateformatter/), делать это при установке изображений не целесообразно 

лучше вынести в экстеншен DateFormatter статическим свойством (как делаем для цветов)

2023-01-08 18:36 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +            guard case .success(_) = result else { return }
```suggestion
            guard case .success = result else { return }
```

2023-01-09 19:28 UTC, merged